import sympy
from mpmath import mp

special_values = {
    'pi': sympy.pi,
    'π': sympy.pi,
    'e': sympy.E,
    'i': sympy.I,
    'γ': sympy.EulerGamma,
    'inf': sympy.oo,
    'oo': sympy.oo,
    '∞': sympy.oo,
    'zinf': sympy.zoo,
    'zoo': sympy.zoo,
    'z∞': sympy.zoo,
    'nan': sympy.nan,
}

def integrate_wrapper(expr, var=None, a=None, b=None):
    if a is None and b is None:
        if var is None:
            return sympy.integrate(expr)
        else:
            return sympy.integrate(expr, var)
    else:
        return sympy.integrate(expr, (var, a, b))

postfix_operators = {
    "N": lambda value: value.evalf(n=mp.dps),
    "evalf": lambda *args: value.evalf(*args),
    "simplify": sympy.simplify,
    "expand": sympy.expand,
    "factor": sympy.factor,
    "cancel": sympy.cancel,
    "apart": sympy.apart,
    "trigsimp": sympy.trigsimp,
    "trigexpand": sympy.expand_trig,
    "powsimp": sympy.powsimp,
    "expexpand": sympy.expand_power_exp,
    "baseexpand": sympy.expand_power_base,
    "powdenest": sympy.powdenest,
    "logexpand": sympy.expand_log,
    "logcombine": sympy.logcombine,
    "funcexpand": sympy.expand_func,
    "gammasimp": sympy.gammasimp,
    "complexexpand": lambda value: value.expand(complex=True),
    "limit": sympy.limit,
    "series": sympy.series,
    "integrate": integrate_wrapper,
    "derivative": lambda *args: sympy.Derivative(*args, evaluate=True),
}

functions = {
    "exp": sympy.exp,
    "log": sympy.log,
    "sqrt": sympy.sqrt,
    "cbrt": sympy.cbrt,
    "re": sympy.re,
    "im": sympy.im,
    "abs": sympy.Abs,
    "arg": sympy.arg,
    "conj": sympy.conjugate,
    "conjugate": sympy.conjugate,
    "sin": sympy.sin,
    "cos": sympy.cos,
    "tan": sympy.tan,
    "cot": sympy.cot,
    "sec": sympy.sec,
    "csc": sympy.csc,
    "asin": sympy.asin,
    "arcsin": sympy.asin,
    "acos": sympy.acos,
    "arccos": sympy.acos,
    "atan": sympy.atan,
    "arctan": sympy.atan,
    "acot": sympy.acot,
    "arccot": sympy.acot,
    "asec": sympy.asec,
    "arcsec": sympy.asec,
    "acsc": sympy.acsc,
    "arccsc": sympy.acsc,
    "atan2": sympy.atan2,
    "sinh": sympy.sinh,
    "cosh": sympy.cosh,
    "tanh": sympy.tanh,
    "coth": sympy.coth,
    "sech": sympy.sech,
    "csch": sympy.csch,
    "asinh": sympy.asinh,
    "arsinh": sympy.asinh,
    "acosh": sympy.acosh,
    "arcosh": sympy.acosh,
    "atanh": sympy.atanh,
    "artanh": sympy.atanh,
    "acoth": sympy.acoth,
    "arcoth": sympy.acoth,
    "asech": sympy.asech,
    "arsech": sympy.asech,
    "acsch": sympy.acsch,
    "arcsch": sympy.acsch,
    "W": sympy.LambertW,
    "LambertW": sympy.LambertW,
    "gamma": sympy.gamma,
    "Γ": sympy.gamma,
    "digamma": sympy.digamma,
    "ψ": sympy.digamma,
    "trigamma": sympy.trigamma,
    "polygamma": sympy.polygamma,
    "uppergamma": sympy.uppergamma,
    "lowergamma": sympy.lowergamma,
    "multigamma": sympy.multigamma,
    "Β": sympy.beta,
    "beta": sympy.beta,
    "erf": sympy.erf,
    "erfc": sympy.erfc,
    "erfi": sympy.erfi,
    "erf2": sympy.erf2,
    "erfinv": sympy.erfinv,
    "erfcinv": sympy.erfcinv,
    "erf2inv": sympy.erf2inv,
    "fresnels": sympy.fresnels,
    "fresnelc": sympy.fresnelc,
    "Ei": sympy.Ei,
    "li": sympy.li,
    "Li": sympy.Li,
    "Si": sympy.Si,
    "Ci": sympy.Ci,
    "Shi": sympy.Shi,
    "Chi": sympy.Chi,
    "besselj": sympy.besselj,
    "bessely": sympy.bessely,
    "besseli": sympy.besseli,
    "besselk": sympy.besselk,
    "hankel1": sympy.hankel1,
    "hankel2": sympy.hankel2,
    "jn": sympy.jn,
    "yn": sympy.yn,
    "marcumq": sympy.marcumq,
    "airyai": sympy.airyai,
    "airybi": sympy.airybi,
    "airyaiprime": sympy.airyaiprime,
    "airybiprime": sympy.airybiprime,
    "zeta": sympy.zeta,
    "ζ": sympy.zeta,
    "dirichlet_eta": sympy.dirichlet_eta,
    "η": sympy.dirichlet_eta,
    "polylog": sympy.polylog,
    "lerchphi": sympy.lerchphi,
    "stieltjes": sympy.stieltjes,
    "elliptic_k": sympy.elliptic_k,
    "elliptic_f": sympy.elliptic_f,
    "elliptic_e": sympy.elliptic_e,
    "elliptic_pi": sympy.elliptic_pi,
    "mathieus": sympy.mathieus,
    "mathieuc": sympy.mathieuc,
    "mathieusprime": sympy.mathieusprime,
    "mathieucprime": sympy.mathieucprime,
    "jacobi": sympy.jacobi,
    "gegenbauer": sympy.gegenbauer,
    "chebyshevt": sympy.chebyshevt,
    "chebyshevu": sympy.chebyshevu,
    "legendre": sympy.legendre,
    "assoc_legendre": sympy.assoc_legendre,
    "hermite": sympy.hermite,
    "hermite_prob": sympy.hermite_prob,
    "laguerre": sympy.laguerre,
    "assoc_laguerre": sympy.assoc_laguerre,
    "Ynm": sympy.Ynm,
    "Znm": sympy.Znm,
    "binomial": sympy.binomial,
    "choose": sympy.binomial,
    "bell": sympy.bell,
    "bernoulli": sympy.bernoulli,
    "catalan": sympy.catalan,
    "euler": sympy.euler,
    "subfactorial": sympy.subfactorial,
    "fibonacci": sympy.fibonacci,
    "harmonic": sympy.harmonic,
    "lucas": sympy.lucas,
    "genocchi": sympy.genocchi,
    "andre": sympy.andre,
    "partition": sympy.partition,
    "divisor_sigma": sympy.divisor_sigma,
    "legendre_symbol": sympy.legendre_symbol,
    "jacobi_symbol": sympy.jacobi_symbol,
    "kronecker_symbol": sympy.kronecker_symbol,
    "mobius": sympy.mobius,
    "primenu": sympy.primenu,
    "primeomega": sympy.primeomega,
    "totient": sympy.totient,
    "reduced_totient": sympy.reduced_totient,
    "primepi": sympy.primepi,
    "stirling": sympy.functions.combinatorial.numbers.stirling,
}
