import sympy

special_values = {
    'pi': sympy.pi,
    'π': sympy.pi,
    'e': sympy.E,
    'i': sympy.I,
    'γ': sympy.EulerGamma,
    'inf': sympy.oo,
    'oo': sympy.oo,
    '∞': sympy.oo,
    'zinf': sympy.zoo,
    'zoo': sympy.zoo,
    'z∞': sympy.zoo,
    'nan': sympy.nan,
}

postfix_operators = {
    "N": lambda value: value.evalf(),
    "evalf": lambda value: value.evalf(),
    "simplify": sympy.simplify,
    "expand": sympy.expand,
    "factor": sympy.factor,
    "cancel": sympy.cancel,
    "apart": sympy.apart,
    "trigsimp": sympy.trigsimp,
    "trigexpand": sympy.expand_trig,
    "powsimp": sympy.powsimp,
    "expexpand": sympy.expand_power_exp,
    "baseexpand": sympy.expand_power_base,
    "powdenest": sympy.powdenest,
    "logexpand": sympy.expand_log,
    "logcombine": sympy.logcombine,
    "funcexpand": sympy.expand_func,
    "gammasimp": sympy.gammasimp,
    "complexexpand": lambda value: value.expand(complex=True),
}

functions = {
    "exp": sympy.exp,
    "log": sympy.log,
    "sqrt": sympy.sqrt,
    "cbrt": sympy.cbrt,
    "re": sympy.re,
    "im": sympy.im,
    "abs": sympy.Abs,
    "arg": sympy.arg,
    "conj": sympy.conjugate,
    "conjugate": sympy.conjugate,
    "sin": sympy.sin,
    "cos": sympy.cos,
    "tan": sympy.tan,
    "cot": sympy.cot,
    "sec": sympy.sec,
    "csc": sympy.csc,
    "asin": sympy.asin,
    "arcsin": sympy.asin,
    "acos": sympy.acos,
    "arccos": sympy.acos,
    "atan": sympy.atan,
    "arctan": sympy.atan,
    "acot": sympy.acot,
    "arccot": sympy.acot,
    "asec": sympy.asec,
    "arcsec": sympy.asec,
    "acsc": sympy.acsc,
    "arccsc": sympy.acsc,
    "sinh": sympy.sinh,
    "cosh": sympy.cosh,
    "tanh": sympy.tanh,
    "coth": sympy.coth,
    "sech": sympy.sech,
    "csch": sympy.csch,
    "asinh": sympy.asinh,
    "arsinh": sympy.asinh,
    "acosh": sympy.acosh,
    "arcosh": sympy.acosh,
    "atanh": sympy.atanh,
    "artanh": sympy.atanh,
    "acoth": sympy.acoth,
    "arcoth": sympy.acoth,
    "asech": sympy.asech,
    "arsech": sympy.asech,
    "acsch": sympy.acsch,
    "arcsch": sympy.acsch,
    "W": sympy.LambertW,
    "LambertW": sympy.LambertW,
    "gamma": sympy.gamma,
    "Γ": sympy.gamma,
    "digamma": sympy.digamma,
    "ψ": sympy.digamma,
    "trigamma": sympy.trigamma,
    "erf": sympy.erf,
    "erfc": sympy.erfc,
    "erfinv": sympy.erfinv,
    "erfcinv": sympy.erfcinv,
    "zeta": sympy.zeta,
    "ζ": sympy.zeta,
}
